In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
import os

print(os.getcwd())

c:\Users\HP\greeshma k\projects\Aircraft-Health-Monitoring\notebooks

In [4]:
import pandas as pd
print("Pandas Imported Successfully")
print(pd.__version__)

Pandas Imported Successfully
3.0.3

In [5]:
import os

print(os.getcwd())
print(os.path.exists("../data/train_FD001.txt"))

c:\Users\HP\greeshma k\projects\Aircraft-Health-Monitoring\notebooks
True

In [6]:
df = pd.read_csv(
    "../data/train_FD001.txt",
    sep=r"\s+",
    header=None
)

print(df.shape)
df.head()

(20631, 26)

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044

In [7]:
columns = ['engine_id', 'cycle']

for i in range(1, 4):
    columns.append(f'op_setting_{i}')

for i in range(1, 22):
    columns.append(f'sensor_{i}')

df.columns = columns

print(df.columns)
df.head()

Index(['engine_id', 'cycle', 'op_setting_1', 'op_setting_2', 'op_setting_3',
       'sensor_1', 'sensor_2', 'sensor_3', 'sensor_4', 'sensor_5', 'sensor_6',
       'sensor_7', 'sensor_8', 'sensor_9', 'sensor_10', 'sensor_11',
       'sensor_12', 'sensor_13', 'sensor_14', 'sensor_15', 'sensor_16',
       'sensor_17', 'sensor_18', 'sensor_19', 'sensor_20', 'sensor_21'],
      dtype='str')

,engine_id,cycle,op_setting_1,op_setting_2,op_setting_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044

In [8]:
rul = df.groupby('engine_id')['cycle'].max().reset_index()

rul.columns = ['engine_id', 'max_cycle']

df = df.merge(rul, on='engine_id', how='left')

df['RUL'] = df['max_cycle'] - df['cycle']

df.head()

,engine_id,cycle,op_setting_1,op_setting_2,op_setting_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21,max_cycle,RUL
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190,192,191
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236,192,190
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442,192,189
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739,192,188
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044,192,187

In [9]:
print(df[['engine_id', 'cycle', 'max_cycle', 'RUL']].head(20))

    engine_id  cycle  max_cycle  RUL
0           1      1        192  191
1           1      2        192  190
2           1      3        192  189
3           1      4        192  188
4           1      5        192  187
5           1      6        192  186
6           1      7        192  185
7           1      8        192  184
8           1      9        192  183
9           1     10        192  182
10          1     11        192  181
11          1     12        192  180
12          1     13        192  179
13          1     14        192  178
14          1     15        192  177
15          1     16        192  176
16          1     17        192  175
17          1     18        192  174
18          1     19        192  173
19          1     20        192  172

In [10]:
print(df.isnull().sum())

engine_id       0
cycle           0
op_setting_1    0
op_setting_2    0
op_setting_3    0
sensor_1        0
sensor_2        0
sensor_3        0
sensor_4        0
sensor_5        0
sensor_6        0
sensor_7        0
sensor_8        0
sensor_9        0
sensor_10       0
sensor_11       0
sensor_12       0
sensor_13       0
sensor_14       0
sensor_15       0
sensor_16       0
sensor_17       0
sensor_18       0
sensor_19       0
sensor_20       0
sensor_21       0
max_cycle       0
RUL             0
dtype: int64

In [11]:
print(df.shape)
print(df.info())

(20631, 28)
<class 'pandas.DataFrame'>
RangeIndex: 20631 entries, 0 to 20630
Data columns (total 28 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   engine_id     20631 non-null  int64
 1   cycle         20631 non-null  int64
 2   op_setting_1  20631 non-null  float64
 3   op_setting_2  20631 non-null  float64
 4   op_setting_3  20631 non-null  float64
 5   sensor_1      20631 non-null  float64
 6   sensor_2      20631 non-null  float64
 7   sensor_3      20631 non-null  float64
 8   sensor_4      20631 non-null  float64
 9   sensor_5      20631 non-null  float64
 10  sensor_6      20631 non-null  float64
 11  sensor_7      20631 non-null  float64
 12  sensor_8      20631 non-null  float64
 13  sensor_9      20631 non-null  float64
 14  sensor_10     20631 non-null  float64
 15  sensor_11     20631 non-null  float64
 16  sensor_12     20631 non-null  float64
 17  sensor_13     20631 non-null  float64
 18  sensor_14     20631 non-null  float64
 19  sensor_15     20631 non-null  float64
 20  sensor_16     20631 non-null  float64
 21  sensor_17     20631 non-null  int64
 22  sensor_18     20631 non-null  int64
 23  sensor_19     20631 non-null  float64
 24  sensor_20     20631 non-null  float64
 25  sensor_21     20631 non-null  float64
 26  max_cycle     20631 non-null  int64
 27  RUL           20631 non-null  int64
dtypes: float64(22), int64(6)
memory usage: 4.4 MB
None

In [12]:
df.to_csv(
    "../data/processed_train.csv",
    index=False
)

print("Processed dataset saved successfully!")

Processed dataset saved successfully!

In [13]:
features = df.drop(
    ['engine_id', 'cycle', 'max_cycle', 'RUL'],
    axis=1
)

target = df['RUL']

print(features.shape)
print(target.shape)

(20631, 24)
(20631,)

In [14]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

features_scaled = scaler.fit_transform(features)

print(features_scaled.shape)

(20631, 24)

In [16]:
import numpy as np

In [17]:
sequence_length = 30

X = []
y = []

for engine_id in df['engine_id'].unique():

    engine_data = df[df['engine_id'] == engine_id]

    engine_features = features_scaled[engine_data.index]

    engine_rul = target.iloc[engine_data.index]

    for i in range(len(engine_data) - sequence_length):

        X.append(
            engine_features[i:i+sequence_length]
        )

        y.append(
            engine_rul.iloc[i+sequence_length]
        )

X = np.array(X)
y = np.array(y)

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (17631, 30, 24)
y shape: (17631,)

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (14104, 30, 24)
X_test: (3527, 30, 24)
y_train: (14104,)
y_test: (3527,)

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

model = Sequential()

model.add(
    LSTM(
        100,
        return_sequences=True,
        input_shape=(30, 24)
    )
)

model.add(Dropout(0.2))

model.add(LSTM(50))

model.add(Dropout(0.2))

model.add(Dense(25))

model.add(Dense(1))

model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

c:\Users\HP\greeshma k\projects\Aircraft-Health-Monitoring\venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 30, 100)        │        50,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 30, 100)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 50)             │        30,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 50)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 25)             │         1,275 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            26 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 81,501 (318.36 KB)

 Trainable params: 81,501 (318.36 KB)

 Non-trainable params: 0 (0.00 B)

In [20]:
history = model.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=64,
    validation_split=0.2
)

Epoch 1/20
177/177 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - loss: 6474.6440 - mae: 62.3504 - val_loss: 3812.6782 - val_mae: 50.1121
Epoch 2/20
177/177 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - loss: 3873.7280 - mae: 50.6469 - val_loss: 3802.1084 - val_mae: 50.2933
Epoch 3/20
177/177 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - loss: 3872.5645 - mae: 50.6573 - val_loss: 3803.1216 - val_mae: 50.3312
Epoch 4/20
177/177 ━━━━━━━━━━━━━━━━━━━━ 5s 25ms/step - loss: 3859.4065 - mae: 50.5916 - val_loss: 3805.7642 - val_mae: 50.3947
Epoch 5/20
177/177 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - loss: 3876.6326 - mae: 50.6524 - val_loss: 3802.2261 - val_mae: 50.2995
Epoch 6/20
177/177 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - loss: 3862.7610 - mae: 50.5905 - val_loss: 3803.9810 - val_mae: 50.1695
Epoch 7/20
177/177 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - loss: 3873.3579 - mae: 50.7107 - val_loss: 3801.7703 - val_mae: 50.2154
Epoch 8/20
177/177 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - loss: 3658.1196 - mae: 48.6281 - val_loss: 2181.7073 - val_mae: 35.9622
Epoch 9/20
177/177 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 1783.7852 - mae: 31.0528 - val_loss: 1329.0020 - val_mae: 26.8588
Epoch 10/20
177/177 ━━━━━━━━━━━━━━━━━━━━ 6s 32ms/step - loss: 1317.1339 - mae: 25.8334 - val_loss: 1025.8243 - val_mae: 21.9439
Epoch 11/20
177/177 ━━━━━━━━━━━━━━━━━━━━ 5s 26ms/step - loss: 1212.9735 - mae: 24.4316 - val_loss: 1014.8680 - val_mae: 21.2226
Epoch 12/20
177/177 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - loss: 1184.8727 - mae: 23.8104 - val_loss: 993.8851 - val_mae: 20.9120
Epoch 13/20
177/177 ━━━━━━━━━━━━━━━━━━━━ 5s 26ms/step - loss: 1138.2340 - mae: 23.3691 - val_loss: 932.6373 - val_mae: 20.5932
Epoch 14/20
177/177 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - loss: 1089.0288 - mae: 22.7039 - val_loss: 1045.5153 - val_mae: 19.8423
Epoch 15/20
177/177 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - loss: 1079.1621 - mae: 22.4263 - val_loss: 957.5717 - val_mae: 21.4005
Epoch 16/20
177/177 ━━━━━━━━━━━━━━━━━━━━ 4s 24ms/step - loss: 1054.6566 - mae: 22.1317 - val_loss: 922.5455 - val_mae: 20.6829
Epoch 17/20
177/177 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - loss: 1047.8264 - mae: 22.1014 - val_loss: 877.9449 - val_mae: 19.7501
Epoch 18/20
177/177 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - loss: 1047.1069 - mae: 21.9821 - val_loss: 908.4645 - val_mae: 19.0922
Epoch 19/20
177/177 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 1025.5702 - mae: 21.8584 - val_loss: 878.8985 - val_mae: 20.2630
Epoch 20/20
177/177 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - loss: 1024.5718 - mae: 21.7386 - val_loss: 874.4393 - val_mae: 19.3688

In [21]:
from sklearn.metrics import mean_squared_error
import numpy as np

predictions = model.predict(X_test)

rmse = np.sqrt(
    mean_squared_error(
        y_test,
        predictions
    )
)

print("RMSE:", rmse)

111/111 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
RMSE: 30.459298413838773

In [25]:
import os

os.makedirs("../models", exist_ok=True)

model.save("../models/aircraft_lstm_model.h5")

print("Model Saved Successfully!")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Model Saved Successfully!

In [26]:
import joblib

joblib.dump(
    scaler,
    "../models/scaler.pkl"
)

print("Scaler Saved Successfully!")

Scaler Saved Successfully!

In [27]:
print(features.columns.tolist())

['op_setting_1', 'op_setting_2', 'op_setting_3', 'sensor_1', 'sensor_2', 'sensor_3', 'sensor_4', 'sensor_5', 'sensor_6', 'sensor_7', 'sensor_8', 'sensor_9', 'sensor_10', 'sensor_11', 'sensor_12', 'sensor_13', 'sensor_14', 'sensor_15', 'sensor_16', 'sensor_17', 'sensor_18', 'sensor_19', 'sensor_20', 'sensor_21']